spring:
  profiles:
    active:
    -  dev
---
spring:
  profiles:  dev    #开发环境
  application:
    name:  microservicecloud_config-atguigu-dev
---
spring:
  profiles:  test   #测试环境
  application:
    name:  microservicecloud_config-atguigu-test
#保存必须是UTF-8格式